version: '{branch}-{build}'

image:
  - Ubuntu1604
  - Visual Studio 2017

environment:
  global:
    CMAKE_BUILD_PARALLEL_LEVEL: 2
  matrix:
    - BUILD_TYPE: Release
    - BUILD_TYPE: Debug

install:
  # set version environment variable
  - ps: $env:GIT_REPO_VERSION = "$(git describe --tags --always)"
  # appveyor workaround: initialize all submodules
  - git submodule update --init --recursive
  # install multilib compilers
  - sh: sudo apt-get -qq update
  - sh: sudo apt-get -qq -y install g++-multilib gcc-multilib
  - sh: "echo g++ version: $(g++ --version | cut -d$'\n' -f1)"

before_build:
  - git clone --branch 'yaml-cpp-0.6.3' --single-branch --recursive --quiet https://github.com/jbeder/yaml-cpp.git
  - ps: cmake -Wno-dev --no-warn-unused-cli -DCMAKE_BUILD_TYPE="$env:BUILD_TYPE" -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 -DCMAKE_INSTALL_PREFIX=yaml-cpp-install -DYAML_CPP_BUILD_CONTRIB=OFF -DYAML_CPP_BUILD_TOOLS=OFF -DYAML_CPP_BUILD_TESTS=OFF -DBUILD_GMOCK=OFF -DYAML_MSVC_SHARED_RT=OFF -S yaml-cpp -B yaml-cpp-build
  - ps: cmake --build yaml-cpp-build --config $env:BUILD_TYPE --target install

build_script:
  - ps: cmake -DCMAKE_BUILD_TYPE="$env:BUILD_TYPE" -Dyaml-cpp_DIR=yaml-cpp-install/share/cmake/yaml-cpp -DLOGCORE_VERSION="$env:GIT_REPO_VERSION" -DLOGCORE_INSTALL_DEV=OFF -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 -S . -B build
  - ps: cmake --build build --target package --config $env:BUILD_TYPE
  - ps: cmake -DCMAKE_BUILD_TYPE="$env:BUILD_TYPE" -Dyaml-cpp_DIR=yaml-cpp-install/share/cmake/yaml-cpp -DLOGCORE_VERSION="$env:GIT_REPO_VERSION" -DLOGCORE_INSTALL_DEV=ON -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 -S . -B build
  - ps: cmake --build build --target package --config $env:BUILD_TYPE

artifacts:
  - path: 'build/*.zip'
  - path: 'build/*.tar.gz'
